Bump jvm from 2.2.21 to 2.3.10 (#472)
Bumps [jvm](https://github.com/JetBrains/kotlin) from 2.2.21 to 2.3.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">jvm's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 2.3.10</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83984"><code>KT-83984</code></a>
Data races around kotlinx.serialization plugin protobuf extensions
registration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83317"><code>KT-83317</code></a>
ClassCastException: with cast kotlin.UInt to java.lang.Number when
defining constant</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83031"><code>KT-83031</code></a>
K2: unstable resolution of EnhancedNullability from type-use NotNull in
presence of unused code</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-81700"><code>KT-81700</code></a>
flaky overload resolution behaviors (false-positive errors, different
final candidates, compile-time failures)</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83983"><code>KT-83983</code></a>
Revert of KT-83081</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83314"><code>KT-83314</code></a>
JSpecify <code>@NullMarked</code> changes Java equals(Object) to
equals(Any?) causing override conflict in Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82863"><code>KT-82863</code></a>
<code>@NoInfer</code> regression since 2.2.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82841"><code>KT-82841</code></a>
&quot;kotlin.NoWhenBranchMatchedException&quot; in <code>when</code>
with <code>!is</code> check &amp; non-sealed class in the middle of
hierarchy</li>
</ul>
<h3>JVM. Reflection</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83608"><code>KT-83608</code></a>
Kotlin-reflect: &quot;Unknown origin of public abstract operator fun
invoke(p1: P1, p2: P2): R&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83361"><code>KT-83361</code></a>
&quot;KotlinReflectionInternalError: Type parameter not found: 0&quot;
on super types with Kotlin 2.3.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-42199"><code>KT-42199</code></a>
&quot;KotlinReflectionInternalError: Unknown origin of public abstract
operator fun invoke&quot; on function reference to FunctionN.invoke</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-81024"><code>KT-81024</code></a>
Reflection: New KType implementation fails on arguments comparison for a
Nothing type parameter</li>
</ul>
<h3>Tools. Compiler Plugins</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83266"><code>KT-83266</code></a>
&quot;Unsupported class file major version 69&quot; for
&quot;produceReleaseComposeMapping&quot; task with Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83099"><code>KT-83099</code></a>
Compose compiler does not generate stack trace mappings for project
files</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83070"><code>KT-83070</code></a>
The KGP api reference is missing a description</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82459"><code>KT-82459</code></a>
Improve iOS simulator boot implementation</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82946"><code>KT-82946</code></a>
Js, Wasm: Upgrade NPM dependencies</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83687"><code>KT-83687</code></a>
Revert deprecation of 'androidTarget' for AGP lower than 9</li>
</ul>
<h2>Kotlin 2.3.10-RC2</h2>
<h2>ChangeLog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83984"><code>KT-83984</code></a>
Data races around kotlinx.serialization plugin protobuf extensions
registration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83983"><code>KT-83983</code></a>
Revert of KT-83081</li>
</ul>
<h2>Kotlin 2.3.10-RC</h2>
<h2>Changelog</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">jvm's
changelog</a>.</em></p>
<blockquote>
<h2>2.3.10</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83984"><code>KT-83984</code></a>
Data races around kotlinx.serialization plugin protobuf extensions
registration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83317"><code>KT-83317</code></a>
ClassCastException: with cast kotlin.UInt to java.lang.Number when
defining constant</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83031"><code>KT-83031</code></a>
K2: unstable resolution of EnhancedNullability from type-use NotNull in
presence of unused code</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-81700"><code>KT-81700</code></a>
flaky overload resolution behaviors (false-positive errors, different
final candidates, compile-time failures)</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83983"><code>KT-83983</code></a>
Revert of KT-83081</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83314"><code>KT-83314</code></a>
JSpecify <code>@NullMarked</code> changes Java equals(Object) to
equals(Any?) causing override conflict in Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82863"><code>KT-82863</code></a>
<code>@NoInfer</code> regression since 2.2.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82841"><code>KT-82841</code></a>
&quot;kotlin.NoWhenBranchMatchedException&quot; in <code>when</code>
with <code>!is</code> check &amp; non-sealed class in the middle of
hierarchy</li>
</ul>
<h3>JVM. Reflection</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83608"><code>KT-83608</code></a>
Kotlin-reflect: &quot;Unknown origin of public abstract operator fun
invoke(p1: P1, p2: P2): R&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83361"><code>KT-83361</code></a>
&quot;KotlinReflectionInternalError: Type parameter not found: 0&quot;
on super types with Kotlin 2.3.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-42199"><code>KT-42199</code></a>
&quot;KotlinReflectionInternalError: Unknown origin of public abstract
operator fun invoke&quot; on function reference to FunctionN.invoke</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-81024"><code>KT-81024</code></a>
Reflection: New KType implementation fails on arguments comparison for a
Nothing type parameter</li>
</ul>
<h3>Tools. Compiler Plugins</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83266"><code>KT-83266</code></a>
&quot;Unsupported class file major version 69&quot; for
&quot;produceReleaseComposeMapping&quot; task with Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83099"><code>KT-83099</code></a>
Compose compiler does not generate stack trace mappings for project
files</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83070"><code>KT-83070</code></a>
The KGP api reference is missing a description</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82459"><code>KT-82459</code></a>
Improve iOS simulator boot implementation</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82946"><code>KT-82946</code></a>
Js, Wasm: Upgrade NPM dependencies</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83687"><code>KT-83687</code></a>
Revert deprecation of 'androidTarget' for AGP lower than 9</li>
</ul>
<h2>2.3.0</h2>
<h3>Analysis API</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-80082"><code>KT-80082</code></a>
K2. False positive &quot;Cannot resolve method&quot; for self-bounded
generic with wildcard return type in Java interop</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-80303"><code>KT-80303</code></a>
Move <code>:native:analysis-api-klib-reader</code> to
<code>:libraries:tools</code></li>
</ul>
<h3>Analysis API. Code Compilation</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-70860"><code>KT-70860</code></a>
K2 IDE / Kotlin Debugger: CCE “java.lang.String cannot be cast to
java.lang.Void” on evaluating not-null variable on the line with
assigning null to that var</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78554"><code>KT-78554</code></a>
K2 IDE / Kotlin Debugger: ISE “No override for FUN
IR_EXTERNAL_DECLARATION_STUB” on calling toString() for local class
instance during evaluation</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/679366a83f99851b42f64795f10ed803ff011c73"><code>679366a</code></a>
Add ChangeLog for 2.3.10-RC2</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/14ba8336989fde2a1dfc53611439207ba61210a8"><code>14ba833</code></a>
Serialization: remove potential data race during extension
registration</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/fb8d334040e27cf5a7cb299c9bb4b0389327a9cc"><code>fb8d334</code></a>
Revert &quot;K2: implement equality for
ConeAttribute.EnhancedNullability&quot;</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/412afb7fb334c8aedc2f1776ecbe5cc5332161f1"><code>412afb7</code></a>
Add ChangeLog for 2.3.10-RC</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/edea41e9c3945240b30a6fa2c68e1bbb9c9f9bd0"><code>edea41e</code></a>
[Gradle] Un-deprecate 'androidTarget()'</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0946452e1cc5e56349f24fb86bdbe203e2a2d6b1"><code>0946452</code></a>
Bump version of the ASM dependency</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/655fb780519cf570d07d506241a46227b8a2a864"><code>655fb78</code></a>
Reflection: always compute JVM signature of built-in functions
manually</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/58d38755f5c1991ee0ba367c0b6de58d85cc93a7"><code>58d3875</code></a>
Fix mergeReleaseComposeMapping task failure when build cache is
enabled</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/56e0a7993ac1c5913a6e0a0bd2f08a09186daef1"><code>56e0a79</code></a>
Copy R8 outputs to Compose folder when transforming obfuscation
file</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/e0eb1746ac5ea0e09e4aa31e757d90b0f5083f24"><code>e0eb174</code></a>
Fix classId for detecting protobuf enums</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v2.2.21...v2.3.10">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jvm&package-manager=gradle&previous-version=2.2.21&new-version=2.3.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>